name: Pages

on:
  push:
    branches:
      - main  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Google urls submit
        run: |
          pwd
          ls -al
          ls -al public source
          cd source
          git clone https://${{ secrets.PRIVATE_REPO_CLONE_TOKEN }}@github.com/persuepersue/google-indexing-api-secret.git temp_google_indexing_api
          cp ./temp_google_indexing_api/ohlinux-blog-1938443474e5.json .
          pip3 install -r requirements.txt
          python3 google_submit_urls.py
          rm -rf temp_google_indexing_api
          git config user.name persuepersue
          git config user.email persuepersue@users.noreply.github.com
          git status
          git add sent.txt
          git commit -m "update sent.txt"
          git push
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: ohlinux.com
          exclude_assets: '.github,sent.txt'
      - name: Checkout to gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Baidu urls submit
        run: |
          curl -H 'Content-Type:text/plain' --data-binary @urls.txt "http://data.zz.baidu.com/urls?site=https://ohlinux.com&token=${{ secrets.BAIDU_TOKEN }}"
      - name: Biying urls submit
        run: |
          urls=`awk '/^https:\/\/ohlinux.com/{T=$0;}{print "\""T"\","}' urls.txt | tr '\n' ' '`
          data='{"siteUrl":"https://ohlinux.com", "urlList":['${urls}']}'
          curl -X POST "https://ssl.bing.com/webmaster/api.svc/json/SubmitUrlBatch?apikey=${{ secrets.BIYING_API }}" -H "Content-Type: application/json" -H "charset: utf-8" -d "${data}"
